// <auto-generated />
namespace DarkBond.ViewModels.Strings
{
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Reflection;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources
    {
        /// <summary>
        /// The resource manager.
        /// </summary>
        private static ResourceManager resourceManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="Resources"/> class.
        /// </summary>
        public Resources()
        {
        }

        /// <summary>
        /// Gets the resource string indexed by the Collapse key.
        /// </summary>
        public static string Collapse
        {
            get
            {
                return Resources.ResourceManager.GetString("Collapse", Resources.Culture);
            }
        }

        /// <summary>
        /// Gets or sets the culture to use for lookups using this strongly typed resource class.
        /// </summary>
        public static CultureInfo Culture { get; set; }

        /// <summary>
        /// Gets the resource string indexed by the Expand key.
        /// </summary>
        public static string Expand
        {
            get
            {
                return Resources.ResourceManager.GetString("Expand", Resources.Culture);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the False key.
        /// </summary>
        public static string False
        {
            get
            {
                return Resources.ResourceManager.GetString("False", Resources.Culture);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Item key.
        /// </summary>
        public static string Item
        {
            get
            {
                return Resources.ResourceManager.GetString("Item", Resources.Culture);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the ItemFormat key.
        /// </summary>
        public static string ItemFormat
        {
            get
            {
                return Resources.ResourceManager.GetString("ItemFormat", Resources.Culture);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Items key.
        /// </summary>
        public static string Items
        {
            get
            {
                return Resources.ResourceManager.GetString("Items", Resources.Culture);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the No key.
        /// </summary>
        public static string No
        {
            get
            {
                return Resources.ResourceManager.GetString("No", Resources.Culture);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Open key.
        /// </summary>
        public static string Open
        {
            get
            {
                return Resources.ResourceManager.GetString("Open", Resources.Culture);
            }
        }

        /// <summary>
        /// Gets the cached ResourceManager instance used by this class.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (Resources.resourceManager == null)
                {
                    Resources.resourceManager = new ResourceManager("DarkBond.ViewModels.Strings.Resources", typeof(Resources).Assembly);
                }

                return Resources.resourceManager;
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the True key.
        /// </summary>
        public static string True
        {
            get
            {
                return Resources.ResourceManager.GetString("True", Resources.Culture);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Yes key.
        /// </summary>
        public static string Yes
        {
            get
            {
                return Resources.ResourceManager.GetString("Yes", Resources.Culture);
            }
        }
    }
}