// <auto-generated />
#pragma warning disable SA1402
#pragma warning disable SA1649
#pragma warning disable CS1591
namespace DarkBond.OrderManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlClient;
    using System.Linq;
    using System.Transactions;
    using DarkBond.ServiceModel;
    using DarkBond.TradingPost;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    /// <summary>
    /// The product.
    /// </summary>
    public class Product
    {
        /// <summary>
        /// The productId.
        /// </summary>
        public Guid ProductId { get; set; }

        /// <summary>
        /// The name.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The description.
        /// </summary>
        public string Description { get; set; }
    }

    [Route("api/[controller]")]
    public class ProductsController : Controller
    {
        private VolatileTransaction volatileTransaction;

        private CommittableTransaction committableTransaction;

        private SqlConnection sqlConnection;

        private bool isCommitted = false;

        private DataModel dataModel;

        protected override void Dispose(bool disposing)
        {
            if (!this.isCommitted)
            {
                this.committableTransaction.Rollback();
            }

            base.Dispose(disposing);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProductsController"/> class.
        /// </summary>
        public ProductsController(DataModel dataModel)
        {
            this.committableTransaction = new CommittableTransaction();
            this.committableTransaction.TransactionCompleted += this.OnTransactionCompleted;

            this.committableTransaction.EnlistVolatile(VolatileTransaction.Current, EnlistmentOptions.None);
            this.sqlConnection = new SqlConnection("Server=tcp:darkbond-development.database.windows.net,1433;Initial Catalog=License Manager;Persist Security Info=False;User ID=DRAirey1;Password=Sc0tl4nd.;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;");
            sqlConnection.Open();
            sqlConnection.EnlistTransaction(this.committableTransaction);

            this.dataModel = dataModel;
        }

        private void OnTransactionCompleted(object sender, TransactionEventArgs e)
        {
            this.isCommitted = true;
        }

        [Authorize]
        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<Product>), 200)]
        public IActionResult Get()
        {
            List<Product> products = new List<Product>();
            try
            {
                foreach (ProductRow productRow in this.dataModel.Product)
                {
                    Product product = new Product();
                    product.Description = productRow.Description;
                    product.Name = productRow.Name;
                    product.ProductId = productRow.ProductId;
                }
            }
            catch
            {

            }
            finally
            {

            }

            return Ok(products);
        }

        [Authorize]
        [HttpGet("{id}")]
        [ProducesResponseType(typeof(IEnumerable<string>), 200)]
        [ProducesResponseType(typeof(void), 404)]
        public IActionResult Get(Guid id)
        {
            Product product = null;
            //if (!this.productRepository.TryGet(id, out product))
            //{
            //    return NotFound();
            //}

            return NotFound();
        }

        [Authorize]
        [HttpPut("{id}")]
        [ProducesResponseType(typeof(void), 200)]
        public IActionResult Put(int id, [FromBody]Product product)
        {
            this.dataModel.CreateProduct(DateTime.Now, DateTime.Now, product.Description, null, product.Name, product.ProductId);
            return Ok();
        }

        [Authorize(Policy = "CanDelete")]
        [HttpDelete("{id}")]
        public void Delete(Guid id, long rowVersion)
        {
            // this.productRepository.Delete(id, rowVersion);
        }
    }

    public interface IProductRepository
    {
        IEnumerable<Product> Get();

        bool TryGet(Guid key, out Product value);

        void Add(Product value);

        bool Delete(Guid key, long rowVersion);
    }

    public class ProductRepository : IProductRepository
    {
        private DataModel dataModel;

        public ProductRepository(DataModel dataModel)
        {
            this.dataModel = dataModel;

            //this.Add(new Product { ProductId = Guid.NewGuid(), Description = "A Fruit", Name = "Orange" });
            //this.Add(new Product { ProductId = Guid.NewGuid(), Description = "A Dairy Product", Name = "Cheese" });
            //this.Add(new Product { ProductId = Guid.NewGuid(), Description = "Breakfast Cereal", Name = "Frosted Flakes" });
        }

        public IEnumerable<Product> Get()
        {
            List<Product> products = new List<Product>();
            //foreach (ProductRow productRow in this.dataModel.Product)
            //{
            //    Product product = new Product();
            //    product.Description = productRow.Description;
            //    product.Name = productRow.Name;
            //    product.ProductId = productRow.ProductId;
            //}

            return products;
        }

        public bool TryGet(Guid key, out Product value)
        {
            ProductRow productRow = this.dataModel.ProductKey.Find(key);
            if (productRow == null)
            {
                value = null;
                return false;
            }

            value = new Product();
            value.ProductId = productRow.ProductId;
            value.Description = productRow.Description;
            value.Name = productRow.Description;
            return true;
        }

        public void Add(Product value)
        {
            this.dataModel.CreateProduct(DateTime.Now, DateTime.Now, value.Description, null, value.Name, Guid.NewGuid());
        }

        public bool Delete(Guid key, long rowVersion)
        {
            //this.dataModel.DeleteProduct(key, rowVersion);
            return true;
        }
    }
}
#pragma warning restore CS1591
#pragma warning restore SA1402
#pragma warning restore SA1649
