//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkBond.TradingPost.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.Location.txt")]
        public string LocationInput {
            get {
                return ((string)(this["LocationInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.Street.txt")]
        public string StreetInput {
            get {
                return ((string)(this["StreetInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.Consumer Debt.txt")]
        public string ConsumerDebtInput {
            get {
                return ((string)(this["ConsumerDebtInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.User.txt")]
        public string UserInput {
            get {
                return ((string)(this["UserInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.NickNames.txt")]
        public string NickNameInput {
            get {
                return ((string)(this["NickNameInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.Organization.txt")]
        public string OrganizationInput {
            get {
                return ((string)(this["OrganizationInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.Address2.txt")]
        public string Address2Input {
            get {
                return ((string)(this["Address2Input"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.MaleSalutations.txt")]
        public string MaleSalutationInput {
            get {
                return ((string)(this["MaleSalutationInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.Consumer.txt")]
        public string ConsumerInput {
            get {
                return ((string)(this["ConsumerInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.MaleNames.txt")]
        public string MaleNamesInput {
            get {
                return ((string)(this["MaleNamesInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.FemaleNames.txt")]
        public string FemaleNamesInput {
            get {
                return ((string)(this["FemaleNamesInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.MaleSuffix.txt")]
        public string MaleSuffixInput {
            get {
                return ((string)(this["MaleSuffixInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.LastNames.txt")]
        public string LastNameInput {
            get {
                return ((string)(this["LastNameInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.PhoneNumbers.txt")]
        public string PhoneNumberInput {
            get {
                return ((string)(this["PhoneNumberInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.FemaleSalutations.txt")]
        public string FemaleSalutationInput {
            get {
                return ((string)(this["FemaleSalutationInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkBond.TradingPost.Data.Files.Credit Card Issuer.txt")]
        public string CreditCardIssuerInput {
            get {
                return ((string)(this["CreditCardIssuerInput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Generated Data\\")]
        public string DataOutputLocation {
            get {
                return ((string)(this["DataOutputLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consumer Debt.xml")]
        public string ConsumerDebtOutput {
            get {
                return ((string)(this["ConsumerDebtOutput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consumer.xml")]
        public string ConsumerOutput {
            get {
                return ((string)(this["ConsumerOutput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Consumer Trust.xml")]
        public string ConsumerTrustOutput {
            get {
                return ((string)(this["ConsumerTrustOutput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("User.xml")]
        public string UserOutput {
            get {
                return ((string)(this["UserOutput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Credit Card.xml")]
        public string CreditCardOutput {
            get {
                return ((string)(this["CreditCardOutput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Organization.xml")]
        public string OrganizationOutput {
            get {
                return ((string)(this["OrganizationOutput"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DumpDataSetToXml {
            get {
                return ((bool)(this["DumpDataSetToXml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DumpDataSetToBinary {
            get {
                return ((bool)(this["DumpDataSetToBinary"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GeneratedTestData_MatchDump.csv")]
        public string CsvMatchDumpFile {
            get {
                return ((string)(this["CsvMatchDumpFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SplitUpOrganizationWorkingOrders {
            get {
                return ((bool)(this["SplitUpOrganizationWorkingOrders"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NumberOfWorkingOrderFilesPerOrganization {
            get {
                return ((int)(this["NumberOfWorkingOrderFilesPerOrganization"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NumberOfImportFilesPerOrganization {
            get {
                return ((int)(this["NumberOfImportFilesPerOrganization"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double PercentageOfConsumerRecordsWithDateOfBirth {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithDateOfBirth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.85")]
        public double PercentageOfCreditCardRecordsWithIssuerData {
            get {
                return ((double)(this["PercentageOfCreditCardRecordsWithIssuerData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double PercentageOfConsumerRecordsWithFirstNames {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithFirstNames"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.95")]
        public double PercentageOfConsumerRecordsWithLastNames {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithLastNames"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.7")]
        public double PercentageOfConsumerRecordsWithPhoneNumber {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithPhoneNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.65")]
        public double PercentageOfConsumerRecordsWithMiddleNames {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithMiddleNames"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double PercentageOfConsumerRecordsWithSuffixes {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithSuffixes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.85")]
        public double PercentageOfConsumerRecordsWithAddress1 {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithAddress1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.18")]
        public double PercentageOfConsumerRecordsWithAddress2 {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithAddress2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.33")]
        public double PercentageOfConsumerRecordsWithBankAccountData {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithBankAccountData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.95")]
        public double PercentageOfConsumerRecordsWithCity {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithCity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double PercentageOfConsumersWithKnownEmployeeStatus {
            get {
                return ((double)(this["PercentageOfConsumersWithKnownEmployeeStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double PercentageOfConsumerRecordsWithSalutations {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithSalutations"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.75")]
        public double PercentageOfConsumerRecordsWithPostalCode {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithPostalCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double PercentageOfConsumerRecordsWithProvinceCode {
            get {
                return ((double)(this["PercentageOfConsumerRecordsWithProvinceCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.09")]
        public double PercentageOfUnemployment {
            get {
                return ((double)(this["PercentageOfUnemployment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseTimeBasedRandomSeed {
            get {
                return ((bool)(this["UseTimeBasedRandomSeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int NumberOfCreditCardsPerConsumer {
            get {
                return ((int)(this["NumberOfCreditCardsPerConsumer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int RandomCreditCardsPerConsumerMax {
            get {
                return ((int)(this["RandomCreditCardsPerConsumerMax"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OneConsumerCreditCardPerDebtHolderOrganization {
            get {
                return ((bool)(this["OneConsumerCreditCardPerDebtHolderOrganization"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DebtSideFuzzCount {
            get {
                return ((int)(this["DebtSideFuzzCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CommonFuzzCount {
            get {
                return ((int)(this["CommonFuzzCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DebtSideFuzzNicknamePercentage {
            get {
                return ((int)(this["DebtSideFuzzNicknamePercentage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("152515115")]
        public string DebtHolderAccountNumberStartValue {
            get {
                return ((string)(this["DebtHolderAccountNumberStartValue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int NumberOfConsumerRecords {
            get {
                return ((int)(this["NumberOfConsumerRecords"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("620")]
        public int NumberOfTrustRecords {
            get {
                return ((int)(this["NumberOfTrustRecords"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int NumberOfDebtRecords {
            get {
                return ((int)(this["NumberOfDebtRecords"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("251")]
        public int NumberOfMatches {
            get {
                return ((int)(this["NumberOfMatches"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("101")]
        public int TrustSideFuzzCount {
            get {
                return ((int)(this["TrustSideFuzzCount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int TrustSideFuzzNicknamePercentage {
            get {
                return ((int)(this["TrustSideFuzzNicknamePercentage"]));
            }
        }
    }
}
