// <auto-generated />
namespace DarkBond.SubscriptionManager.Common.Strings
{
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Reflection;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources
    {
        /// <summary>
        /// The resource manager.
        /// </summary>
        private static ResourceManager resourceManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="Resources"/> class.
        /// </summary>
        public Resources()
        {
        }

        /// <summary>
        /// Gets the resource string indexed by the AddCustomerOperation key.
        /// </summary>
        public static string AddCustomerOperation
        {
            get
            {
                return Resources.ResourceManager.GetString("AddCustomerOperation", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Address1 key.
        /// </summary>
        public static string Address1
        {
            get
            {
                return Resources.ResourceManager.GetString("Address1", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the ApplicationName key.
        /// </summary>
        public static string ApplicationName
        {
            get
            {
                return Resources.ResourceManager.GetString("ApplicationName", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Cancel key.
        /// </summary>
        public static string Cancel
        {
            get
            {
                return Resources.ResourceManager.GetString("Cancel", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the City key.
        /// </summary>
        public static string City
        {
            get
            {
                return Resources.ResourceManager.GetString("City", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the ClearSelection key.
        /// </summary>
        public static string ClearSelection
        {
            get
            {
                return Resources.ResourceManager.GetString("ClearSelection", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Content key.
        /// </summary>
        public static string Content
        {
            get
            {
                return Resources.ResourceManager.GetString("Content", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Count key.
        /// </summary>
        public static string Count
        {
            get
            {
                return Resources.ResourceManager.GetString("Count", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Country key.
        /// </summary>
        public static string Country
        {
            get
            {
                return Resources.ResourceManager.GetString("Country", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets or sets the culture to use for lookups using this strongly typed resource class.
        /// </summary>
        public static CultureInfo CultureInfo { get; set; }

        /// <summary>
        /// Gets the resource string indexed by the Customer key.
        /// </summary>
        public static string Customer
        {
            get
            {
                return Resources.ResourceManager.GetString("Customer", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the CustomerProperties key.
        /// </summary>
        public static string CustomerProperties
        {
            get
            {
                return Resources.ResourceManager.GetString("CustomerProperties", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Delete key.
        /// </summary>
        public static string Delete
        {
            get
            {
                return Resources.ResourceManager.GetString("Delete", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the DeleteCustomerOperation key.
        /// </summary>
        public static string DeleteCustomerOperation
        {
            get
            {
                return Resources.ResourceManager.GetString("DeleteCustomerOperation", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Description key.
        /// </summary>
        public static string Description
        {
            get
            {
                return Resources.ResourceManager.GetString("Description", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Details key.
        /// </summary>
        public static string Details
        {
            get
            {
                return Resources.ResourceManager.GetString("Details", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the DetailsPane key.
        /// </summary>
        public static string DetailsPane
        {
            get
            {
                return Resources.ResourceManager.GetString("DetailsPane", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Edit key.
        /// </summary>
        public static string Edit
        {
            get
            {
                return Resources.ResourceManager.GetString("Edit", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Email key.
        /// </summary>
        public static string Email
        {
            get
            {
                return Resources.ResourceManager.GetString("Email", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the FilesUpToDate key.
        /// </summary>
        public static string FilesUpToDate
        {
            get
            {
                return Resources.ResourceManager.GetString("FilesUpToDate", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the FirstName key.
        /// </summary>
        public static string FirstName
        {
            get
            {
                return Resources.ResourceManager.GetString("FirstName", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Home key.
        /// </summary>
        public static string Home
        {
            get
            {
                return Resources.ResourceManager.GetString("Home", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Identifier key.
        /// </summary>
        public static string Identifier
        {
            get
            {
                return Resources.ResourceManager.GetString("Identifier", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the LastName key.
        /// </summary>
        public static string LastName
        {
            get
            {
                return Resources.ResourceManager.GetString("LastName", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Layout key.
        /// </summary>
        public static string Layout
        {
            get
            {
                return Resources.ResourceManager.GetString("Layout", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the License key.
        /// </summary>
        public static string License
        {
            get
            {
                return Resources.ResourceManager.GetString("License", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the LicenseProperties key.
        /// </summary>
        public static string LicenseProperties
        {
            get
            {
                return Resources.ResourceManager.GetString("LicenseProperties", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Name key.
        /// </summary>
        public static string Name
        {
            get
            {
                return Resources.ResourceManager.GetString("Name", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the NavigationPane key.
        /// </summary>
        public static string NavigationPane
        {
            get
            {
                return Resources.ResourceManager.GetString("NavigationPane", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the New key.
        /// </summary>
        public static string New
        {
            get
            {
                return Resources.ResourceManager.GetString("New", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the NewCustomer key.
        /// </summary>
        public static string NewCustomer
        {
            get
            {
                return Resources.ResourceManager.GetString("NewCustomer", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the NewLicense key.
        /// </summary>
        public static string NewLicense
        {
            get
            {
                return Resources.ResourceManager.GetString("NewLicense", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the NewProduct key.
        /// </summary>
        public static string NewProduct
        {
            get
            {
                return Resources.ResourceManager.GetString("NewProduct", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the OK key.
        /// </summary>
        public static string OK
        {
            get
            {
                return Resources.ResourceManager.GetString("OK", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Open key.
        /// </summary>
        public static string Open
        {
            get
            {
                return Resources.ResourceManager.GetString("Open", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Organize key.
        /// </summary>
        public static string Organize
        {
            get
            {
                return Resources.ResourceManager.GetString("Organize", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Panes key.
        /// </summary>
        public static string Panes
        {
            get
            {
                return Resources.ResourceManager.GetString("Panes", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Phone key.
        /// </summary>
        public static string Phone
        {
            get
            {
                return Resources.ResourceManager.GetString("Phone", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the PostalCode key.
        /// </summary>
        public static string PostalCode
        {
            get
            {
                return Resources.ResourceManager.GetString("PostalCode", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Product key.
        /// </summary>
        public static string Product
        {
            get
            {
                return Resources.ResourceManager.GetString("Product", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the ProductProperties key.
        /// </summary>
        public static string ProductProperties
        {
            get
            {
                return Resources.ResourceManager.GetString("ProductProperties", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Properties key.
        /// </summary>
        public static string Properties
        {
            get
            {
                return Resources.ResourceManager.GetString("Properties", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Province key.
        /// </summary>
        public static string Province
        {
            get
            {
                return Resources.ResourceManager.GetString("Province", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Rename key.
        /// </summary>
        public static string Rename
        {
            get
            {
                return Resources.ResourceManager.GetString("Rename", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the cached ResourceManager instance used by this class.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (Resources.resourceManager == null)
                {
                    Resources.resourceManager = new ResourceManager("DarkBond.SubscriptionManager.Common.Strings.Resources", typeof(Resources).GetTypeInfo().Assembly);
                }

                return Resources.resourceManager;
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Select key.
        /// </summary>
        public static string Select
        {
            get
            {
                return Resources.ResourceManager.GetString("Select", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the SelectAll key.
        /// </summary>
        public static string SelectAll
        {
            get
            {
                return Resources.ResourceManager.GetString("SelectAll", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the SignIn key.
        /// </summary>
        public static string SignIn
        {
            get
            {
                return Resources.ResourceManager.GetString("SignIn", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the SubscriptionId key.
        /// </summary>
        public static string SubscriptionId
        {
            get
            {
                return Resources.ResourceManager.GetString("SubscriptionId", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Subscriptions key.
        /// </summary>
        public static string Subscriptions
        {
            get
            {
                return Resources.ResourceManager.GetString("Subscriptions", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the Tiles key.
        /// </summary>
        public static string Tiles
        {
            get
            {
                return Resources.ResourceManager.GetString("Tiles", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the UpdateCustomer key.
        /// </summary>
        public static string UpdateCustomer
        {
            get
            {
                return Resources.ResourceManager.GetString("UpdateCustomer", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the UpdateCustomerOperation key.
        /// </summary>
        public static string UpdateCustomerOperation
        {
            get
            {
                return Resources.ResourceManager.GetString("UpdateCustomerOperation", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the UpdateProduct key.
        /// </summary>
        public static string UpdateProduct
        {
            get
            {
                return Resources.ResourceManager.GetString("UpdateProduct", Resources.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the View key.
        /// </summary>
        public static string View
        {
            get
            {
                return Resources.ResourceManager.GetString("View", Resources.CultureInfo);
            }
        }
    }
}